# Generated by Django 6.0.3 on 2026-03-05 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Публичный идентификатор'),
        ),
    ]
