# Generated by Django 6.0.3 on 2026-03-07 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fill_order_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор'),
        ),
    ]
