# Generated by Django 6.0.3 on 2026-03-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram chat id'),
        ),
        migrations.AddField(
            model_name='order',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram message id'),
        ),
    ]
