# Generated by Django 6.0.3 on 2026-03-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_telegram_chat_id_order_telegram_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код зоны доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название зоны доставки'),
        ),
    ]
