# Generated by Django 6.0.3 on 2026-03-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_options_productimage_created_at_and_more'),
        ('core', '0008_businesslunchday_businesslunchweek_and_more'),
        ('orders', '0006_order_delivery_fee_order_delivery_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lunch_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.businesslunchday'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
    ]
