# Generated by Django 6.0.3 on 2026-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_lunch_day_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('upon_receipt', 'Оплата при получении (наличные/перевод)'), ('online', 'Оплата онлайн')], default='upon_receipt', max_length=24, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=32, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки по промокоду'),
        ),
    ]
