# Generated by Django 6.0.3 on 2026-03-14 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_payment_method_order_promo_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный идентификатор платежа')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='ID платежа в ЮKassa')),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Idempotence Key')),
                ('provider_status', models.CharField(blank=True, max_length=32, verbose_name='Статус ЮKassa')),
                ('confirmation_url', models.URLField(blank=True, verbose_name='Ссылка на оплату')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='Ответ ЮKassa')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('fulfillment', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=20, verbose_name='Способ получения')),
                ('payment_method', models.CharField(choices=[('upon_receipt', 'Оплата при получении (наличные/перевод)'), ('online', 'Оплата онлайн')], default='online', max_length=24, verbose_name='Способ оплаты')),
                ('customer_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('customer_comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Адрес строкой')),
                ('address_entrance', models.CharField(blank=True, max_length=20, verbose_name='Подъезд')),
                ('address_floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж')),
                ('address_apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира/офис')),
                ('delivery_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта доставки')),
                ('delivery_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота доставки')),
                ('delivery_zone_code', models.CharField(blank=True, max_length=64, verbose_name='Код зоны доставки')),
                ('delivery_zone_name', models.CharField(blank=True, max_length=120, verbose_name='Название зоны доставки')),
                ('items_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма товаров')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('promo_code', models.CharField(blank=True, max_length=32, verbose_name='Промокод')),
                ('promo_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки по промокоду')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итого к оплате')),
                ('cart_snapshot', models.JSONField(blank=True, default=list, verbose_name='Снимок корзины')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_payment_attempt', to='orders.order', verbose_name='Созданный заказ')),
            ],
            options={
                'verbose_name': 'Онлайн-оплата',
                'verbose_name_plural': 'Онлайн-оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
