# Generated by Django 6.0.3 on 2026-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(upload_to='promo_banners/', verbose_name='Изображение')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Промо-баннер',
                'verbose_name_plural': 'Промо-баннеры',
                'ordering': ['sort_order', '-created_at', 'id'],
            },
        ),
    ]
