# Generated by Django 6.0.3 on 2026-03-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='Принимаем заказы')),
                ('site_notice', models.CharField(blank=True, max_length=255, verbose_name='Сообщение на сайте')),
                ('working_hours_text', models.CharField(blank=True, default='Ежедневно, 10:00–22:00', max_length=255, verbose_name='Текст режима работы')),
                ('phone', models.CharField(blank=True, default='+7 (000) 000-00-00', max_length=32, verbose_name='Телефон')),
                ('address_text', models.CharField(blank=True, default='г. Ижевск, кафе «Сказка»', max_length=255, verbose_name='Адрес')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки кафе',
                'verbose_name_plural': 'Настройки кафе',
            },
        ),
    ]
