# Generated by Django 6.0.3 on 2026-03-11 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesettings',
            name='closing_time',
            field=models.TimeField(default=datetime.time(22, 0), verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='cafesettings',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Принимаем заказы вручную'),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='working_hours_text',
            field=models.CharField(blank=True, default='Ежедневно, 10:00–23:00', max_length=255, verbose_name='Текст режима работы'),
        ),
    ]
