# Generated by Django 6.0.3 on 2026-03-11 17:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cafesettings_closing_time_cafesettings_opening_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название зоны')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код зоны')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Стоимость доставки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Минимальная сумма заказа для зоны')),
                ('polygon_json', models.TextField(help_text='JSON-массив точек вида [[lon, lat], [lon, lat], ...]. Минимум 3 точки.', verbose_name='Полигон JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Зоны доставки',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки по умолчанию'),
        ),
        migrations.AlterField(
            model_name='cafesettings',
            name='working_hours_text',
            field=models.CharField(blank=True, default='Ежедневно, 10:00–22:00', max_length=255, verbose_name='Текст режима работы'),
        ),
    ]
