# Generated by Django 6.0.3 on 2026-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliveryzone_alter_cafesettings_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesettings',
            name='yandex_maps_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yandex Maps API key'),
        ),
    ]
