# Generated by Django 6.0.3 on 2026-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cafesettings_yandex_maps_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafesettings',
            name='yandex_suggest_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='Yandex Suggest API key'),
        ),
    ]
