# Generated by Django 6.0.3 on 2026-03-12 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cafesettings_yandex_suggest_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Меню бизнес-ланчей',
                'verbose_name_plural': 'Меню бизнес-ланчей',
                'ordering': ['-week_start', 'sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLunchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, upload_to='business_lunches/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.businesslunchmenu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Позиция бизнес-ланча',
                'verbose_name_plural': 'Позиции бизнес-ланча',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
