# Generated by Django 6.0.3 on 2026-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businesslunchmenu_businesslunchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('banquets', 'Банкеты'), ('catering', 'Кейтеринг')], max_length=32, unique=True, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Основной текст')),
                ('features', models.TextField(blank=True, help_text='По одному пункту с новой строки.', verbose_name='Преимущества / условия')),
                ('cta_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок CTA')),
                ('cta_text', models.TextField(blank=True, verbose_name='Текст CTA')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница услуги',
                'verbose_name_plural': 'Страницы услуг',
                'ordering': ['page_type'],
            },
        ),
    ]
