# Generated by Django 6.0.3 on 2026-03-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productimage_options_productimage_created_at_and_more'),
        ('core', '0007_servicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLunchDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=160, verbose_name='Название дня')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена бизнес-ланча')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'День бизнес-ланча',
                'verbose_name_plural': 'Дни бизнес-ланчей',
                'ordering': ['service_date', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLunchWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок недели')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('week_start', models.DateField(verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Неделя бизнес-ланчей',
                'verbose_name_plural': 'Недели бизнес-ланчей',
                'ordering': ['-week_start', 'sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessLunchDayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Например: "Салат", "Суп", "Горячее", "Напиток".', max_length=80, verbose_name='Роль / категория')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.businesslunchday', verbose_name='День')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_lunch_day_items', to='catalog.product', verbose_name='Товар из меню')),
            ],
            options={
                'verbose_name': 'Позиция дня бизнес-ланча',
                'verbose_name_plural': 'Позиции дней бизнес-ланчей',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='businesslunchday',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.businesslunchweek', verbose_name='Неделя'),
        ),
        migrations.DeleteModel(
            name='BusinessLunchItem',
        ),
        migrations.DeleteModel(
            name='BusinessLunchMenu',
        ),
        migrations.AddConstraint(
            model_name='businesslunchday',
            constraint=models.UniqueConstraint(fields=('week', 'service_date'), name='unique_business_lunch_day_per_week_date'),
        ),
    ]
