# Generated by Django 6.0.3 on 2026-03-18 12:00

import datetime

from django.db import migrations, models


def populate_schedule_fields(apps, schema_editor):
    CafeSettings = apps.get_model("core", "CafeSettings")
    CafeSettings.objects.all().update(
        working_hours_text="Ежедневно, 10:00–21:00",
        opening_time=datetime.time(10, 0),
        closing_time=datetime.time(21, 0),
        order_hours_text="Ежедневно, 10:00–20:00",
        order_opening_time=datetime.time(10, 0),
        order_closing_time=datetime.time(20, 0),
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_businesslunchday_businesslunchweek_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafesettings",
            name="working_hours_text",
            field=models.CharField(
                blank=True,
                default="Ежедневно, 10:00–21:00",
                max_length=255,
                verbose_name="Текст режима работы",
            ),
        ),
        migrations.AlterField(
            model_name="cafesettings",
            name="closing_time",
            field=models.TimeField(
                default=datetime.time(21, 0),
                verbose_name="Время закрытия",
            ),
        ),
        migrations.AddField(
            model_name="cafesettings",
            name="order_closing_time",
            field=models.TimeField(
                default=datetime.time(20, 0),
                verbose_name="Окончание приема заказов",
            ),
        ),
        migrations.AddField(
            model_name="cafesettings",
            name="order_hours_text",
            field=models.CharField(
                blank=True,
                default="Ежедневно, 10:00–20:00",
                max_length=255,
                verbose_name="Текст приема заказов",
            ),
        ),
        migrations.AddField(
            model_name="cafesettings",
            name="order_opening_time",
            field=models.TimeField(
                default=datetime.time(10, 0),
                verbose_name="Начало приема заказов",
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="page_type",
            field=models.CharField(
                choices=[
                    ("banquets", "Банкеты"),
                    ("catering", "Кейтеринг"),
                    ("children_parties", "Детские праздники"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Тип страницы",
            ),
        ),
        migrations.RunPython(populate_schedule_fields, noop_reverse),
    ]
